name: Continuous Integration

on: [push, pull_request]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.2"
      - name: Install vmdfmt
        run: go install github.com/bobertlo/vmd/cmd/vmdfmt@latest
      - name: Check formatting
        run: |
          export PATH="$PATH:/tmp/go/bin:$(pwd)/node_modules/.bin"
          ./ci/check_format.sh

  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@v1
